shfmt scripts, 1px borders, red sel border

diff --git a/bin/wacom-setup b/bin/wacom-setup
--- a/bin/wacom-setup
+++ b/bin/wacom-setup
@@ -5,16 +5,16 @@ output="HDMI-0"
 device_found=false
 
 for i in $(seq 5); do
-    if xsetwacom list devices | grep -q "Wacom"; then
-	device_found=true
-	break
-    fi
-    sleep "$i"
+	if xsetwacom list devices | grep -q "Wacom"; then
+		device_found=true
+		break
+	fi
+	sleep "$i"
 done
 
 if [ "$device_found" = false ]; then
-    echo "$0: device not found"
-    exit 1
+	echo "$0: device not found"
+	exit 1
 fi
 
 list="$(xsetwacom list devices)"
@@ -22,8 +22,8 @@ pad="$(echo "$list" | awk '/pad/{print $7}')"
 stylus="$(echo "$list" | awk '/stylus/{print $7}')"
 
 if [ -z "$pad" ]; then
-    echo "$0: pad is empty"
-    exit 1
+	echo "$0: pad is empty"
+	exit 1
 fi
 
 xsetwacom set "$stylus" MapToOutput "$output"
